# Generated by Django 3.1.6 on 2021-02-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='title_updated',
        ),
    ]
